---

- name: ansible playbook
  ignore_errors: yes
  hosts: localhost
  vars:
    passfile: /Users/vyang/Desktop/testing/output/PASSWD-perm.txt
    passwd: /Users/vyang/Desktop/testing/output/PASSWD-file.txt
    shadow: /Users/vyang/Desktop/testing/output/SHADOW-file.txt
    group: /Users/vyang/Desktop/testing/output/GROUPS-file.txt
  tasks:


  - name: 5.5.3 Ensure default group for the root account is GID 0
    shell: 'grep ^root: {{ passwd }} | cut -f4 -d:'
    register: out_926
    failed_when: >
      out_926.stdout != '0'
  # - debug: msg={{ out_926.stdout }}
    # Print all contents of the shell task's output.

  - name: 6.1.2 Ensure permissions on /etc/passwd are configured 
    shell: grep ^-rw-r--r-- {{ passfile }}
    register: ps
    failed_when: >
      '-rw-r--r--'  not in ps.stdout
  # - debug: msg={{ ps.stdout }}

  - name: "6.2.1 | AUDIT | Ensure accounts in /etc/passwd use shadowed passwords | Get users not using shadowed passwords"
    shell: awk -F':' '($2 != "x" ) { print $1}' {{ passwd }}
    register: out621
  
  - name: "AUTOMATED | 6.2.1 | AUDIT | Ensure accounts in /etc/passwd use shadowed passwords | Alert on findings"
    debug:
      msg:
        - "ALERT! You have users that are not using a shadowed password. Please convert the below accounts to use a shadowed password"
        - "{{ out621.stdout_lines }}"

  - name: "AUTOMATED | 6.2.2 | PATCH | Ensure password fields are not empty"
    shell: awk -F":" '($2 == "" ) { print $1 }' {{ shadow }}
    register: out622

  - name: "AUTOMATED | 6.2.2 | PATCH | Ensure password fields are not empty | Lock users with empty password"
    user:
      name: "{{ item }}"
      password_lock: yes
    with_items:
        - "{{ out622.stdout_lines }}"
    when: out622.stdout | length > 0
 
  - name: "AUTOMATED | 6.2.3 | PATCH | Ensure no legacy + entries exist in /etc/passwd"
    shell: grep '^+:' {{ passwd }}
    register: out623
    failed_when: >
      out623.stdout != ''

  - name: 6.2.6 Ensure root is the only UID 0 account
    shell: awk -F':' '($3 == 0) { print $1 }' {{ passwd }} | grep -qx 'root'
    register: out626
    failed_when: out626.stdout != ''
  # - debug: msg={{ out_925.stdout }}

  - name: "AUTOMATED | 6.2.11 | PATCH | Ensure root is the only UID 0 account"
    shell: awk -F":" '($3 == 0 && $1 != \"root\") {i++;print $1 }' {{ passwd }} 
    register: out6211
    failed_when: false
    # when: out6211.stdout | length > 0
  
  - name: "AUTOMATED | 6.2.13 | AUDIT | Ensure no duplicate UIDs exist | Check for duplicate UIDs"
    shell: "pwck -r | awk -F: '{if ($3 in uid) print $1 ; else uid[$3]}' {{passwd}}"
    failed_when: false
    register: out6213
    # when: out621.stdout | length > 0
 
  - name: "AUTOMATED | 6.2.13 | AUDIT | Ensure no duplicate UIDs exist | Print message that no duplicate UIDs exist"
    debug:
        msg: "Good News! There are no duplicate UID's in the system"
    when: out6213.stdout | length == 0

  - name: "AUTOMATED | 6.2.13 | AUDIT | Ensure no duplicate UIDs exist | Print warning about users with duplicate UIDs"
    debug:
        msg: "Warning!!!! The following users have UIDs that are duplicates: {{ out6213.stdout_lines }}"
    when: out6213.stdout | length > 0


  
  # - name: "AUTOMATED | 6.2.14 | AUDIT | Ensure no duplicate GIDs exist"
    # block:
  - name: "AUTOMATED | 6.2.14 | AUDIT | Ensure no duplicate GIDs exist | Check for duplicate GIDs"
    shell: "pwck -r | awk -F: '{if ($3 in users) print $1 ; else users[$3]}' {{group}}"
    changed_when: no
    failed_when: no
    check_mode: false
    register: ubtu20cis_6_2_14_user_user_check

  - name: "AUTOMATED | 6.2.14 | AUDIT | Ensure no duplicate GIDs exist | Print message that no duplicate GID's exist"
    debug:
        msg: "Good News! There are no duplicate GIDs in the system"
    when: ubtu20cis_6_2_14_user_user_check.stdout | length == 0

  - name: "AUTOMATED | 6.2.14 | AUDIT | Ensure no duplicate GIDs exist | Print warning about users with duplicate GIDs"
    debug:
        msg: "Warning: The following groups have duplicate GIDs: {{ ubtu20cis_6_2_14_user_user_check.stdout_lines }}"
    when: ubtu20cis_6_2_14_user_user_check.stdout | length > 0
    # when:
    #   - ubtu20cis_rule_6_2_14

  - name: "AUTOMATED | 6.2.15 | AUDIT | Ensure no duplicate user names exist | Check for duplicate User Names"
    shell: "pwck -r | awk -F: '{if ($1 in users) print $1 ; else users[$1]}' {{passwd}}"
    changed_when: no
    failed_when: no
    check_mode: false
    register: ubtu20cis_6_2_15_user_username_check

  - name: "AUTOMATED | 6.2.15 | AUDIT | Ensure no duplicate user names exist | Print message that no duplicate user names exist"
    debug:
        msg: "Good News! There are no duplicate user names in the system"
    when: ubtu20cis_6_2_15_user_username_check.stdout | length == 0

  - name: "AUTOMATED | 6.2.15 | AUDIT | Ensure no duplicate user names exist | Print warning about users with duplicate User Names"
    debug:
        msg: "Warning: The following user names are duplicates: {{ ubtu20cis_6_2_15_user_username_check.stdout_lines }}"
    when: ubtu20cis_6_2_15_user_username_check.stdout | length > 0

  - name: "AUTOMATED | 6.2.17 | AUDIT | Ensure shadow group is empty | Get Shadow GID"
    shell: grep ^shadow {{group}} | cut -f3 -d":"
    changed_when: false
    failed_when: false
    check_mode: false
    register: ubtu20cis_6_2_17_shadow_gid

  - name: "AUTOMATED | 6.2.17 | AUDIT | Ensure shadow group is empty | List of users with Shadow GID"
    shell: awk -F":" '($4 == "{{ ubtu20cis_6_2_17_shadow_gid.stdout }}") { print }' {{passwd}} | cut -f1 -d":"
    changed_when: false
    failed_when: false
    check_mode: false
    register: ubtu20cis_6_2_17_users_shadow_gid

  - name: "AUTOMATED | 6.2.17 | AUDIT | Ensure shadow group is empty | Message on no users"
    debug:
        msg: "Good News! There are no users with the Shadow GID on your system"
    when: ubtu20cis_6_2_17_users_shadow_gid.stdout | length == 0

  - name: "AUTOMATED | 6.2.17 | AUDIT | Ensure shadow group is empty | Message on users with Shadow GID"
    debug:
        msg:
            - "WARNING!!!! There are users that are in the Shadow group"
            - "To conform to CIS standards no users should be in this group"
            - "Please move the users below into another group"
            - "{{ ubtu20cis_6_2_17_users_shadow_gid.stdout_lines }}"
    when: ubtu20cis_6_2_17_users_shadow_gid.stdout | length > 0