---

- name: ansible playbook
  ignore_errors: yes
  hosts: localhost

  tasks:
  - include_vars: file_vars.yaml
  
  - name: Check syslog.conf configuration
    shell: cat {{ syslogconf }}
    register: out141
    failed_when: out141.stdout != ''
  # - debug: msg={{ out141.stdout }}

  - name: check login logs
    shell: cat {{ logs }}
    register: out142
    failed_when: out142.stdout == ''
  # - debug: msg={{ out142.stdout }}


