---

- name: ansible playbook
  ignore_errors: yes
  hosts: localhost

  tasks:
  - include_vars: file_vars.yaml
  
  - name: Check restrictive permissions on the keydirs files
    shell: cat {{ keydirs }} 
    register: out91
    failed_when: out91.stdout == ''
  # - debug: msg={{ out91.stdout }}

