---

- name: ansible playbook
  ignore_errors: yes
  hosts: localhost

  tasks:
  - include_vars: file_vars.yaml
  
  - name: Check restrictive permissions on the var-spool-cron files
    shell: cat {{ varspoolcron }} 
    register: out71
    failed_when: out71.stdout == ''
  # - debug: msg={{ out71.stdout }}

